// Generated by gencpp from file comms/Num.msg
// DO NOT EDIT!


#ifndef COMMS_MESSAGE_NUM_H
#define COMMS_MESSAGE_NUM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace comms
{
template <class ContainerAllocator>
struct Num_
{
  typedef Num_<ContainerAllocator> Type;

  Num_()
    : x(0)  {
    }
  Num_(const ContainerAllocator& _alloc)
    : x(0)  {
  (void)_alloc;
    }



   typedef int16_t _x_type;
  _x_type x;





  typedef boost::shared_ptr< ::comms::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::comms::Num_<ContainerAllocator> const> ConstPtr;

}; // struct Num_

typedef ::comms::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::comms::Num > NumPtr;
typedef boost::shared_ptr< ::comms::Num const> NumConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::comms::Num_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::comms::Num_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace comms

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'comms': ['/home/cassie/HybridLab/ROSNET/src/comms/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::comms::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::comms::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comms::Num_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::comms::Num_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comms::Num_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::comms::Num_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::comms::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9470b35d49b33d38ac38411578bdbbce";
  }

  static const char* value(const ::comms::Num_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9470b35d49b33d38ULL;
  static const uint64_t static_value2 = 0xac38411578bdbbceULL;
};

template<class ContainerAllocator>
struct DataType< ::comms::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "comms/Num";
  }

  static const char* value(const ::comms::Num_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::comms::Num_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 x\n\
";
  }

  static const char* value(const ::comms::Num_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::comms::Num_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Num_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::comms::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::comms::Num_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int16_t>::stream(s, indent + "  ", v.x);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COMMS_MESSAGE_NUM_H
